In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
def pool2d(X, pool_size, mode="max"):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(0, Y.shape[0]):
        for j in range(0, Y.shape[1]):
            if mode == "max":
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == "avg":
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [4]:
pool2d(X, (2, 2), "avg")

tensor([[2., 3.],
        [5., 6.]])

In [5]:
#Pooling using pytorch pooling layer
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [6]:
#By default in pytorch the size of pooling window and stride is same.
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [7]:
#Pooling with multiple channels
X = torch.cat((X, X + 1), 1)
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

In [8]:
#Implementing average pooling through covolution.
#Consider we have a kernel of size 2x2, to compute average pooling using this kernel we need each value in kernel to be 0.25

K = torch.tensor([[0.25, 0.25], [0.25, 0.25]])
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
Y = d2l.torch.conv2d(X.reshape(1, 1, 3, 3), K.reshape(1, 1, 2, 2))
Y

tensor([[[[2., 3.],
          [5., 6.]]]])

In [9]:
import torch.nn.functional as F


In [41]:
def average_pooling_conv(input_tensor, pooling_size):
    batch_size, channels, height, width = input_tensor.size()
    kernel_size = (pooling_size, pooling_size)

    kernel = torch.ones((channels, 1, pooling_size, pooling_size)) / pooling_size*pooling_size
    print(kernel)
    output = F.conv2d(input_tensor, kernel, stride=1, padding=0, groups=channels)
    return output

In [42]:
input = torch.rand((1, 3, 28, 28))
output = average_pooling_conv(input, 3)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
